import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Demo de Next </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Welcome a about
        </h1>
        <p className={styles.description}>
          Get started by editing{' '}
          <a href="/">Come back!</a>
        </p>
       </main>
    </div>
  )
}
